[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=0.3.23",
    "fastapi>=0.128.0",
    "ollama>=0.6.1",
    "pydantic>=2.12.5",
    "uvicorn>=0.40.0",
]
