[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "chromadb==0.5.20",
    "fastapi==0.115.0",
    "ollama==0.3.3",
    "pydantic==2.9.2",
    "pydantic-settings==2.6.1",
    "ruff>=0.14.13",
    "uvicorn==0.30.0",
    "websockets>=16.0",
]
